const LIST = {
  REQUEST: "POSTS_LIST_REQUEST",
  SUCCESS: "POSTS_LIST_SUCCESS",
  ERROR: "POSTS_LIST_ERROR",
  RESET: "POSTS_LIST_RESET",
};

const DETAILS = {
  REQUEST: "POSTS_DETAILS_REQUEST",
  SUCCESS: "POSTS_DETAILS_SUCCESS",
  ERROR: "POSTS_DETAILS_ERROR",
  RESET: "POSTS_DETAILS_RESET",
};



export const PostActionTypes = {
  POSTS_LIST: LIST,
  DETAILS: DETAILS
};
